### ISSUE TITLE
Get-WinEvent : The parameter is incorrect in PS 5

### ISSUE THREAD

**Issue by imorandinwnp** [oneoffdallas/nagios_scripts#1]
Hi!,

Excellent work here.
I've been using this script for a time now.

In PS 5 I get this error:

```
Get-WinEvent : The parameter is incorrect
At C:\scripts\check_veeam_endpoint_backups.ps1:68 
char:15
+ ... ogEntries = Get-WinEvent -MaxEvents $ArgMaxEntries -FilterHashtable $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WinEvent], EventLogExcept 
   ion
    + FullyQualifiedErrorId : System.Diagnostics.Eventing.Reader.EventLogExcep 
   tion,Microsoft.PowerShell.Commands.GetWinEventCommand
```
 
Backup failed: backup job has not run in last 24 hours 
  
Backup failed: backup job has not run in last 24 hours |'BackupNotRun'=1 

Thanks,

Ignacio

**Comment by effmgt** [comment]
In case anyone else comes across this issue.
I had the same thing on a new Win 2019 Server and Veeam Agent 3.0.1039.

The backup job was only called the <ServerName>, the script was looking for "*Veeam Agent `'Backup Job*" on line 73. I renamed the Backup job on the server to "Backup Job <ServerName>" and re-ran. Worked perfectly.
