### ISSUE TITLE
Jobs with spaces & symbols don't work

### ISSUE THREAD

**Issue by sawft99** [oneoffdallas/nagios_scripts#3]
In  Nagios when creating the NCPA check/query you provide plugin/check_veeam_eventlogs.ps1/Job Name/hours

If the job name has spaces it doesn't seem to work. I've tried wrapping it with '' and "" marks with no change

Error in Nagios service

```
Cannot convert value "VMs" to type "System.Int32". Error: "Input string was not in a correct format."
At C:\\Program Files\\Nagios\\NCPA\\plugins\\check_veeam_eventlogs.ps1:78 char:1
+ $Filter = @{
+ ~~~~~~~~~~~~
+ CategoryInfo : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvalidCastFromStringToInteger

Backup failed: backup job Repete has not run in last VMs hours

Backup failed: backup job Repete has not run in last VMs hours

```

**Comment by sawft99** [comment]
I've fixed this in my own [fork](https://github.com/sawft99/nagios_scripts/blob/sawft99-dev/check_veeam_eventlogs.ps1)

The check_ncpa command needs to be used a bit differently though.

`-t 'TOKEN' -P 5693 -M 'plugins/check_veeam_eventlogs.ps1/Veeam Job Name 72'`

I also have it working with symbols, or at least dashes but the format would need to be a bit different

`-t 'TOKEN' -P 5693 -M 'plugins/check_veeam_eventlogs.ps1/"Veeam - Job Name" 72'`

For uniformity I'll just stick with the second option

**Comment by oneoffdallas** [comment]
Looks great! Thank you for your contribution!
